### ISSUE TITLE
error

### ISSUE THREAD

**Issue by helmiw** [kopijahe/wifiid-openwrt#1]
curl: (6) Couldn't resolve host 'welcome2.wifi.id'

**Comment by kopijahe** [comment]
Coba cara ini:
1. login ke router
2. Masuk ke `Network` -> `Hostnames`
3. Tekan tombol `Add`
4. Masukkan `welcome2.wifi.id` di bagian hostname dan `10.233.16.32` (atau kalau tidak bisa: `10.233.16.32`) di bagian IP
5. Tekan tombol `Add` lagi
6. Masukkan `lp.wifi.id` sebagai hostname dan `36.86.63.19` (atau kalau tidak bisa: `36.91.226.203`) sebagai IP
7. Tekan tombol `Save & Apply`

Lalu dicoba lagi script-nya...

Kalau berhasil, nanti saya tambahkan di tutorialnya.

**Comment by kopijahe** [comment]
Tadi saya konfirmasi di salah satu tempat yang saya pasang script ini, sudah bisa jalan lagi setelah melakukan hal di atas. Jadi saya close dulu.

**Comment by helmiw** [comment]
Matur suwun mas, sudah seminggu ini aman
