### ISSUE TITLE
saat di sh /etc/rc.local muncul pesan 404

### ISSUE THREAD

**Issue by supri717** [kopijahe/wifiid-openwrt#10]
saat setelah instalasi dan menjalankan sh /etc/rc.local muncul pesan
"/etc/autologin.sh: line 1: 404:: not found"

ini kenapa ya

**Comment by kopijahe** [comment]
Autologin versi `autologin.sh` sudah tidak saya dukung, silahkan gunakan autologin `kopijahe` sesuai petunjuk di dokumennya.
