### ISSUE TITLE
CURL: 28 & 7

### ISSUE THREAD

**Issue by apriady** [kopijahe/wifiid-openwrt#12]
Pada salah satu jaringan WMS yg saya miliki, sering mendapatkan error seperti berikut:
> Percobaan login. Interface: wwan1. Hasil: login tidak berhasil, kode status CURL: 28 & 7

Detail kondisi di lokasi:
- Setup multiwan
- tipe produk wms lite

error curl 28 & 7 ini biasanya disebabkan oleh apa ya?

**Comment by kopijahe** [comment]
Kalau pada posisi load-balancing/mwan3, penyebabnya bisa dari banyak hal, termasuk pengaturan mwan3 itu sendiri.

Untuk status cURL sendiri, kode 7 artinya server tidak bisa dihubungi, dan 28 artinya timeout. Kode selengkapnya bisa merujuk ke halaman [ini](https://curl.se/libcurl/c/libcurl-errors.html) atau bisa juga [ini](https://everything.curl.dev/usingcurl/returns).

**Comment by apriady** [comment]
Noted, mungkin akan saya coba tanpa mwan3 dulu untuk cek penyebab utamanya di mana.
akan saya update lagi hasilnya nanti.
Thanks

**Comment by kopijahe** [comment]
Karena tidak ada kabar lanjutan, issue ini saya tutup dulu.
