### ISSUE TITLE
Error cUrl 3

### ISSUE THREAD

**Issue by unexposedindonesia** [kopijahe/wifiid-openwrt#13]
Saya menggunakan wms, autologin kopijahe error curl 3 

`Percobaan login. Interface: wwan. Hasil: login tidak berhasil, kode status CURL: 3
`

**Comment by kopijahe** [comment]
Di bawah status itu juga tertulis: ```Pengaturan belum lengkap, silahkan ulangi konfigurasi```.

Bisa merujuk [tutorial di blog](https://blog.kopijahe.my.id/posts/autologin-kopijahe/) untuk langkah selanjutnya.
