### ISSUE TITLE
curL return code 3 & 6

### ISSUE THREAD

**Issue by kennynugraha** [kopijahe/wifiid-openwrt#14]
Halo gan, saya mengalami script tidak berfungsi. konfigurasi yang saya gunakan hanya wireless client dengan interface wwan yang menembak wifi.id-lanjutkan, ketika saya coba lihat syslognya muncul pesan user.notice dengan error curL 3 & 6, permasalahan ini sebenarnya saya paham bahwa script tidak bisa menemukan hostname welcome2.wifi.id padahal saya sudah set di bagian Hostname menu di openwrt.

Anehnya ketika saya coba buka captive portalnya melalui handphone maupun laptop, welcome2.wifi.id terdeteksi. Saat ini saya berasumsi bahwa script yang diinstall di openwrt saya tidak bisa terhubung dengan hostname dari wifi.id karena mengggunakan parameter -d dan saya masukkan url manual tetap tidak bisa, Mohon bantuannya...

**Comment by kopijahe** [comment]
Bisa coba disertakan hasil dari perintah `kopijahe -r` ? bagian username dan password jika hendak disensor, silahkan.

**Comment by kennynugraha** [comment]
> Bisa coba disertakan hasil dari perintah `kopijahe -r` ? bagian username dan password jika hendak disensor, silahkan.

root@Galaxy-A33:~# kopijahe -r
Pengaturan autologin:

kopijahe.@autologin[0]=autologin
kopijahe.@autologin[0].multi_autologin='0'
kopijahe.@autologin[0].loadbalance='no'
kopijahe.@autologin[0].cpcprovider='kopijahe'
kopijahe.@autologin[0].cpcretry='2'
kopijahe.@autologin[0].cpctimeout='3'
kopijahe.@autologin[0].cpcuseping='true'
kopijahe.@autologin[0].sleeptime='8'
kopijahe.@autologin[0].password='ijahe'
kopijahe.@autologin[0].wifivariant='wifi.id-lanjutkan'
kopijahe.@autologin[0].tipelogin='/'

Versi aplikasi: 2.6.4
OpenWrt version: 21.02.3
Device model: Bolt BL201
Random ID: ljLh
Jumlah autologin berjalan: 1

==========
/etc/rc.local:
# Put your custom commands here that should be executed once
# the system init finished. By default this file does nothing.
iw reg set US
/etc/init.d/network restart
/bin/sh /etc/led-internet-indicator.sh &
sleep 20
kopijahe &
exit 0

==========
Hostnames:
dhcp.@domain[0]=domain
dhcp.@domain[0].name='lp.wifi.id'
dhcp.@domain[0].ip='36.91.226.203'
dhcp.@domain[1]=domain
dhcp.@domain[1].name='welcome3.wifi.id'
dhcp.@domain[1].ip='118.98.34.148'
dhcp.@domain[2]=domain
dhcp.@domain[2].name='welcome2.wifi.id'
dhcp.@domain[2].ip='10.233.16.13'
dhcp.@domain[3]=domain
dhcp.@domain[3].name='logout.wifi.id'
dhcp.@domain[3].ip='10.233.16.13'

==========
System log:
Wed Oct 11 11:38:44 2023 user.notice kopijahe 2.6.4: Percobaan login. Interface: . Hasil: login tidak berhasil, kode status CURL: 6 & 3
Wed Oct 11 11:38:44 2023 user.notice kopijahe 2.6.4: Pengaturan belum lengkap, silahkan ulangi konfigurasi
Wed Oct 11 11:39:05 2023 user.notice kopijahe 2.6.4: Percobaan login. Interface: . Hasil: login tidak berhasil, kode status CURL: 6 & 3
Wed Oct 11 11:39:05 2023 user.notice kopijahe 2.6.4: Pengaturan belum lengkap, silahkan ulangi konfigurasi
Wed Oct 11 11:39:26 2023 user.notice kopijahe 2.6.4: Percobaan login. Interface: . Hasil: login tidak berhasil, kode status CURL: 6 & 3
Wed Oct 11 11:39:26 2023 user.notice kopijahe 2.6.4: Pengaturan belum lengkap, silahkan ulangi konfigurasi
Wed Oct 11 11:39:46 2023 user.notice kopijahe 2.6.4: Percobaan login. Interface: . Hasil: login tidak berhasil, kode status CURL: 6 & 3

**Comment by kopijahe** [comment]
Gunakan `kopijahe -d`, lalu paste-kan URL login-nya, dan dicoba login manual menggunakan `kopijahe -z`. Bagaimana hasilnya?

**Comment by kopijahe** [comment]
Karena tidak ada balasan, maka saya tutup dulu.

**Comment by kennynugraha** [comment]
> Gunakan `kopijahe -d`, lalu paste-kan URL login-nya, dan dicoba login manual menggunakan `kopijahe -z`. Bagaimana hasilnya?

Halo gan, saya coba return curl 0 & 3 saat ini. Kira2 kenapa ya?

**Comment by kopijahe** [comment]
Itu karena pengaturan URL login-nya tidak ada/lengkap.

**Comment by kennynugraha** [comment]
> Itu karena pengaturan URL login-nya tidak ada/lengkap.

Oh ya saya mau info juga gan kalau ini wms lanjutkan free tanpa username password, lalu mac address saya random setiap reboot, ini barusan saya coba ketika urlnya saya ganti dengan mac yang baru saja reboot dia bisa login. Solusinya apa ya gan kalau mau pakai parameter '-d' apakah?

**Comment by kopijahe** [comment]
Soal MAC address yang berubah-ubah setiap boot, itu permasalahan dari router-nya (karena partisi "factory" rusak/kosong kalau di mt7620/mt7621, misal: bolt bl100/bl201) dan di luar lingkup script autologin.

Solusi yang bisa saya berikan ya antara perbaiki partisinya, atau set manual MAC address-nya.

**Comment by kennynugraha** [comment]
> Soal MAC address yang berubah-ubah setiap boot, itu permasalahan dari router-nya (karena partisi "factory" rusak/kosong kalau di mt7620/mt7621, misal: bolt bl100/bl201) dan di luar lingkup script autologin.
> 
> Solusi yang bisa saya berikan ya antara perbaiki partisinya, atau set manual MAC address-nya.

Kalau semisal mac address sudah di fixkan, apakah parameter '-d' ini cukup sekali di set di awal dengan mac address yang sudah saya "fix" kan tadi dan bisa auto login terus ya?

**Comment by kopijahe** [comment]
Parameter `-a` dan `-d` hanya perlu dilakukan satu kali saja di awal. Tidak perlu diulangi, kecuali ada kendala (misal URL-nya mengalami perubahan signifikan).

Meskipun MAC address berubah-ubah setiap boot, script juga secara otomatis mendeteksi dan menggunakan MAC yang terbaru, dan selama saya tes, tetap login otomatis.
