### ISSUE TITLE
Tanya brick c60

### ISSUE THREAD

**Issue by amandadamar01** [kopijahe/wifiid-openwrt#5]
C60 v3 habis upgrade openwrt brick lampu lan nha tapi g bisa di ping ip nya

**Comment by kopijahe** [comment]
Permasalahan bukan di script saya, tapi saya coba bantu ya...

Coba di unbrick melalui TFTP sesuai di postingan di forum openwrt ini: https://forum.openwrt.org/t/help-in-unbricking-tp-link-archer-c60-v3/62642/19
