### ISSUE TITLE
Wireless is not associated

### ISSUE THREAD

**Issue by helmiw** [kopijahe/wifiid-openwrt#6]
Habis scan wifi.id malah Wireless is not associated, itu apanya ya mas?

**Comment by kopijahe** [comment]
Perangkatnya (pemancar dan penangkap sinyal) apa saja?  
Jarak antara pemancar dan penangkap?  
Apa ada halangan (misal tembok, pohon)?

**Comment by kopijahe** [comment]
Karena tidak ada jawaban, dan masalahnya bukan di aplikasi/script autologin, maka saya tutup dulu laporannya. Jika masih terkendala, silahkan dilanjutkan dengan memberi komentar di bawah.

**Comment by helmiw** [comment]
Sudah bisa mas, tapi kalau perangkat reboot "Wireless is not associated" lagi, padahal sudah saya tambahkan sleep 10 && sebelum baris /bin/sh /etc/autologin.sh & di berkas /etc/rc.local

**Comment by kopijahe** [comment]
Coba ganti pakai script kopijahe saja, karena script lama sudah tidak ada pengembangan lagi.

https://blog.kopijahe.my.id/posts/autologin-kopijahe/
